### ISSUE TITLE
Removing the 25 card limit in class

### ISSUE THREAD

**Issue by k4yf0ur** [AA2Hackanon/AA2Face#9]
Hey, someone who claimed to be you recently posted in the thread, so I thought to try to contact you here as well. Wanna try removing the 25 card limit in class? 
I hooked the functions to add/remove cards to the class so we could technically store all their play data somewhere and then cycle the cards each day or each period or something, while restoring their play data. But this implementation is pretty ass, and it'd be much cooler if we could directly increase the size of the class while allowing more than 25 cards to be in the class simultaneously. This requires some arcane magic, so I thought to seek out the magicman himself. Would appreciate if you responded through github instead of the thread, so that we know we're actually talking to you and not some shitposter. Cheers.

Oh and also soon enough people are going to hit the max limit for personalities in the maker UI. I think there's only one row of slots left and they were asking if you could update aa2face to increase the available slots.

**Comment by AA2Hackanon** [comment]
Im afraid the only magic i had was way too much time and nothing to do with it. I don't know (or remember enough about what i saw) to tell if such a change is possible to do in a realistic timeframe, but you probably know more about AA2 internals than me at this point, so that question doesnt make me very confident that it is.

I can do the personality thing tho.

**Comment by linkanon** [comment]
Unlimiting the personalities would be great. Probably best way would be to do it the same thing you do for the hairs: the normal buttons and a spinner at the bottom.

**Comment by k4yf0ur** [comment]
Hey man! Damn, we thought you were dead. I don't personally know you, but I'm glad you're alive and well. 
Alright no worries, it would've been an ambitious undertaking anyway. Do you play the game still? 
Oh and another thing, we've started a patreon a while ago. We've decided that the money is shared between us for past contribution to AAU, not just future development. So even if you never intend to touch AAU again we'll be happy to give you a share. It ain't much, but after a while it's enough to buy a game or two. Drop by [discord ](https://discord.gg/N37M9Ny) sometimes!
